const data = {
	products: [
		{
			_id: '1',
			name: 'Nike Slim Shirt',
			category: 'Shirts',
			image: 'https://soccerstore.azureedge.net/714-714-59832.png',
			price: 120,
			countInStock: 10,
			brand: 'Nike',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			_id: '2',
			name: 'Adidas Fit Shirt',
			category: 'Shirts',
			image: 'https://soccerstore.azureedge.net/714-714-93596.png',
			price: 100,
			countInStock: 20,
			brand: 'Adidas',
			rating: 3.8,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			_id: '3',
			name: 'Lacoste Free Shirt',
			category: 'Shirts',
			image: 'https://photos6.spartoo.it/photos/160/16026929/16026929_500_A.jpg',
			price: 220,
			countInStock: 0,
			brand: 'Lacoste',
			rating: 4.8,
			numReviews: 17,
			description: 'high quality product',
		},
		{
			_id: '4',
			name: 'Nike Slim Pant',
			category: 'Pants',
			image: 'https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/2fcca62a-10c2-497a-b1bd-6907f87e4678/pantaloni-da-calcio-fc-barcelona-vaporknit-strike-thwkhD.png',
			price: 78,
			countInStock: 15,
			brand: 'Nike',
			rating: 2.5,
			numReviews: 1,
			description: 'high quality product',
		},
		{
			_id: '5',
			name: 'Puma Slim Pant',
			category: 'Pants',
			image: 'https://www.futbolemotion.com/imagesarticulos/135430/grandes/pantalon-largo-puma-ess-slim-pants-fl-cotton-black-0.jpg',
			price: 65,
			countInStock: 5,
			brand: 'Puma',
			rating: 4.5,
			numReviews: 10,
			description: 'high quality product',
		},
		{
			_id: '6',
			name: 'Adidas Fit Pant',
			category: 'Pants',
			image: 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/e68e7eb46caa441ab87aa962007e3262_9366/Tiro_19_Training_Pants_Black_D95957_01_laydown.jpg',
			price: 139,
			countInStock: 12,
			brand: 'Adidas',
			rating: 4.5,
			numReviews: 15,
			description: 'high quality product',
		},
	],
};
export default data;
